/*
 * Panelek létrehozása
 */
package hhqcs.form.comco;

import hhqcs.HHQCSServer;

/**
 *
 * @author Gabesz
 */
public class JpanelTitle extends javax.swing.JPanel {
    
    @SuppressWarnings("FieldMayBeFinal")
    private HHQCSServer server;

    /**
     * Creates new form JpanelForm
     *
     * @param server HHQCSServer
     */
    @SuppressWarnings("CallToThreadStartDuringObjectConstruction")
    public JpanelTitle() {
       initComponents();
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        machineName = new javax.swing.JLabel();
        liveSignal = new javax.swing.JLabel();
        dataLastMessageTime = new javax.swing.JLabel();
        thicknessLastMessageTime = new javax.swing.JLabel();
        sapLastSentCoilId = new javax.swing.JLabel();
        SAPCount = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 228, 21));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        setFocusable(false);
        setMinimumSize(new java.awt.Dimension(950, 38));
        setName(""); // NOI18N
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(950, 38));
        setLayout(new java.awt.GridBagLayout());

        machineName.setBackground(new java.awt.Color(204, 204, 204));
        machineName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        machineName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        machineName.setText("Berendezés");
        machineName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        machineName.setFocusable(false);
        machineName.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        machineName.setMaximumSize(new java.awt.Dimension(120, 22));
        machineName.setMinimumSize(new java.awt.Dimension(20, 22));
        machineName.setName(""); // NOI18N
        machineName.setPreferredSize(new java.awt.Dimension(120, 22));
        machineName.setRequestFocusEnabled(false);
        machineName.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(machineName, gridBagConstraints);

        liveSignal.setBackground(new java.awt.Color(0, 0, 0, .3f));
        liveSignal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        liveSignal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        liveSignal.setText("Életjel");
        liveSignal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        liveSignal.setFocusable(false);
        liveSignal.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        liveSignal.setMaximumSize(new java.awt.Dimension(140, 24));
        liveSignal.setMinimumSize(new java.awt.Dimension(140, 24));
        liveSignal.setName(""); // NOI18N
        liveSignal.setPreferredSize(new java.awt.Dimension(140, 24));
        liveSignal.setRequestFocusEnabled(false);
        liveSignal.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        add(liveSignal, gridBagConstraints);

        dataLastMessageTime.setBackground(new java.awt.Color(204, 204, 204));
        dataLastMessageTime.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        dataLastMessageTime.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dataLastMessageTime.setText("Minősített Adatok");
        dataLastMessageTime.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dataLastMessageTime.setFocusable(false);
        dataLastMessageTime.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        dataLastMessageTime.setMaximumSize(new java.awt.Dimension(200, 24));
        dataLastMessageTime.setMinimumSize(new java.awt.Dimension(200, 24));
        dataLastMessageTime.setPreferredSize(new java.awt.Dimension(200, 24));
        dataLastMessageTime.setRequestFocusEnabled(false);
        dataLastMessageTime.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(dataLastMessageTime, gridBagConstraints);

        thicknessLastMessageTime.setBackground(new java.awt.Color(0, 0, 0, .3f));
        thicknessLastMessageTime.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        thicknessLastMessageTime.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        thicknessLastMessageTime.setText("Vastagság");
        thicknessLastMessageTime.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        thicknessLastMessageTime.setFocusable(false);
        thicknessLastMessageTime.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        thicknessLastMessageTime.setMaximumSize(new java.awt.Dimension(120, 24));
        thicknessLastMessageTime.setMinimumSize(new java.awt.Dimension(120, 24));
        thicknessLastMessageTime.setName(""); // NOI18N
        thicknessLastMessageTime.setPreferredSize(new java.awt.Dimension(120, 24));
        thicknessLastMessageTime.setRequestFocusEnabled(false);
        thicknessLastMessageTime.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(thicknessLastMessageTime, gridBagConstraints);

        sapLastSentCoilId.setBackground(new java.awt.Color(204, 204, 204));
        sapLastSentCoilId.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        sapLastSentCoilId.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sapLastSentCoilId.setText("Tekercsszám");
        sapLastSentCoilId.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        sapLastSentCoilId.setFocusable(false);
        sapLastSentCoilId.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        sapLastSentCoilId.setMaximumSize(new java.awt.Dimension(140, 24));
        sapLastSentCoilId.setMinimumSize(new java.awt.Dimension(140, 24));
        sapLastSentCoilId.setName(""); // NOI18N
        sapLastSentCoilId.setPreferredSize(new java.awt.Dimension(140, 24));
        sapLastSentCoilId.setRequestFocusEnabled(false);
        sapLastSentCoilId.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        add(sapLastSentCoilId, gridBagConstraints);

        SAPCount.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SAPCount.setText("ORACLE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        add(SAPCount, gridBagConstraints);

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SAPCount;
    private javax.swing.JLabel dataLastMessageTime;
    private javax.swing.JLabel liveSignal;
    private javax.swing.JLabel machineName;
    private javax.swing.JLabel sapLastSentCoilId;
    private javax.swing.JLabel thicknessLastMessageTime;
    // End of variables declaration//GEN-END:variables
}
